// packages/web/src/components/ComposerBar.vue
<script setup lang="ts">
import { CornerDownLeft, ImagePlus, Square, X } from "lucide-vue-next";
import { computed, nextTick, onBeforeUnmount, ref, watch } from "vue";
import type { ConnectionStatus } from "../composables/useBridgeClient";
import type {
  RpcImageContent,
  RpcSlashCommand,
  RpcWorkspaceEntry,
} from "../shared-types";
import {
  COMPOSER_ATTACHMENT_ACCEPT,
  createComposerAttachments,
  extractSupportedImageFiles,
  formatAttachmentSize,
  toRpcImageContent,
  type ComposerAttachment,
} from "../utils/attachments";
import type { RpcModelInfo } from "../utils/models";
import {
  applyWorkspaceMentionCompletion,
  getWorkspaceMentionContext,
  getWorkspaceMentionSuggestions,
  type WorkspaceMentionSuggestion,
} from "../utils/workspaceMentions";
import CommandPalette from "./CommandPalette.vue";
import ModelDropdown from "./ModelDropdown.vue";
import WorkspaceMentionPalette from "./WorkspaceMentionPalette.vue";

const THINKING_LEVEL_OPTIONS = [
  { value: "off", label: "Off" },
  { value: "minimal", label: "Minimal" },
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
  { value: "xhigh", label: "XHigh" },
] as const;

const props = defineProps<{
  connectionStatus: ConnectionStatus;
  isStreaming: boolean;
  commands: RpcSlashCommand[];
  workspaceEntries: RpcWorkspaceEntry[];
  workspaceEntriesLoading: boolean;
  ensureWorkspaceEntries: () => Promise<RpcWorkspaceEntry[]>;
  models: RpcModelInfo[];
  selectedModel: RpcModelInfo | null;
  thinkingLevel: string | null;
  autoCompactionEnabled: boolean;
}>();

const emit = defineEmits<{
  submit: [payload: { message: string; images: RpcImageContent[] }];
  abort: [];
  selectModel: [model: RpcModelInfo];
  selectThinkingLevel: [level: string];
  toggleAutoCompaction: [enabled: boolean];
}>();

const MAX_TEXTAREA_HEIGHT = 160;

const inputText = ref("");
const textareaRef = ref<HTMLTextAreaElement | null>(null);
const fileInputRef = ref<HTMLInputElement | null>(null);
const isDisabled = computed(() => props.connectionStatus !== "connected");
const paletteRef = ref<InstanceType<typeof CommandPalette> | null>(null);
const mentionPaletteRef = ref<InstanceType<
  typeof WorkspaceMentionPalette
> | null>(null);
const attachments = ref<ComposerAttachment[]>([]);
const isDragActive = ref(false);
const attachmentNotice = ref<string | null>(null);
const cursorOffset = ref(0);
const dismissedMentionKey = ref<string | null>(null);

const showPalette = ref(false);
const filterText = computed(() => {
  if (!showPalette.value) return "";
  return inputText.value.slice(1);
});
const mentionContext = computed(() => {
  if (showPalette.value) return null;
  return getWorkspaceMentionContext(inputText.value, cursorOffset.value);
});
const mentionSuggestions = computed(() => {
  if (!mentionContext.value) return [];
  return getWorkspaceMentionSuggestions(
    props.workspaceEntries,
    mentionContext.value,
  );
});
const showMentionPalette = computed(() => {
  if (showPalette.value || !mentionContext.value) return false;
  if (dismissedMentionKey.value === getMentionKey(mentionContext.value)) {
    return false;
  }
  if (props.workspaceEntriesLoading) return true;
  return true;
});
const currentModelText = computed(() => {
  if (!props.selectedModel)
    return props.models.length > 0 ? "choose model" : "no models";
  return `${props.selectedModel.provider}/${props.selectedModel.id}`;
});
const selectedThinkingLevel = computed(() => {
  if (props.thinkingLevel === "normal") return "medium";
  return props.thinkingLevel ?? "off";
});
const selectedThinkingLabel = computed(
  () =>
    THINKING_LEVEL_OPTIONS.find(
      option => option.value === selectedThinkingLevel.value,
    )?.label ?? "Off",
);
const thinkingSelectWidth = computed(
  () => `calc(${selectedThinkingLabel.value.length + 1.5}ch + 84px)`,
);
const normalizedInputText = computed(() =>
  normalizeSubmittedText(inputText.value),
);
const showStopButton = computed(() => props.isStreaming);
const hasAttachments = computed(() => attachments.value.length > 0);
const canSubmit = computed(
  () =>
    !isDisabled.value &&
    (normalizedInputText.value.length > 0 || hasAttachments.value),
);
const canAbort = computed(() => !isDisabled.value && props.isStreaming);
const attachmentSummary = computed(() => {
  if (attachmentNotice.value) return attachmentNotice.value;
  if (!attachments.value.length) return "";
  if (attachments.value.length === 1) return "1 image attached";
  return `${attachments.value.length} images attached`;
});

let attachmentNoticeTimer: ReturnType<typeof setTimeout> | null = null;
let dragDepth = 0;

function normalizeSubmittedText(value: string): string {
  const normalized = value.replace(/\r\n/g, "\n");
  const lines = normalized.split("\n");

  while (lines.length > 0 && lines[0].trim() === "") {
    lines.shift();
  }
  while (lines.length > 0 && lines[lines.length - 1].trim() === "") {
    lines.pop();
  }

  if (lines.length === 0) return "";

  lines[0] = lines[0].trimStart();
  lines[lines.length - 1] = lines[lines.length - 1].trimEnd();
  return lines.join("\n");
}

function getMentionKey(
  mention: ReturnType<typeof getWorkspaceMentionContext> | null,
): string | null {
  if (!mention) return null;
  return `${mention.start}:${mention.prefix}`;
}

function syncCursorFromTextarea() {
  const el = textareaRef.value;
  cursorOffset.value = el?.selectionStart ?? inputText.value.length;
}

function resizeTextarea() {
  nextTick(() => {
    const el = textareaRef.value;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, MAX_TEXTAREA_HEIGHT)}px`;
    el.style.overflowY =
      el.scrollHeight > MAX_TEXTAREA_HEIGHT ? "auto" : "hidden";
  });
}

watch(inputText, val => {
  showPalette.value = val.startsWith("/");
  if (showPalette.value) {
    dismissedMentionKey.value = null;
  }
  resizeTextarea();
  nextTick(() => {
    syncCursorFromTextarea();
  });
});

watch(mentionContext, (mention, previousMention) => {
  const mentionKey = getMentionKey(mention);
  if (mentionKey && mentionKey !== getMentionKey(previousMention)) {
    dismissedMentionKey.value = null;
  }

  if (mention) {
    void props.ensureWorkspaceEntries();
  }
});

function clearAttachmentNotice() {
  if (attachmentNoticeTimer) {
    clearTimeout(attachmentNoticeTimer);
    attachmentNoticeTimer = null;
  }
  attachmentNotice.value = null;
}

function setAttachmentNotice(message: string | null) {
  clearAttachmentNotice();
  attachmentNotice.value = message;
  if (!message) return;
  attachmentNoticeTimer = setTimeout(() => {
    attachmentNotice.value = null;
    attachmentNoticeTimer = null;
  }, 4000);
}

async function addAttachmentsFromFiles(
  files: Iterable<File> | ArrayLike<File> | null | undefined,
) {
  if (!files) return;

  const incomingFiles = Array.from(files);
  if (!incomingFiles.length) return;

  const { attachments: nextAttachments, rejectedNames } =
    await createComposerAttachments(incomingFiles);

  if (nextAttachments.length > 0) {
    attachments.value = [...attachments.value, ...nextAttachments];
    setAttachmentNotice(null);
  }

  if (rejectedNames.length > 0) {
    setAttachmentNotice(
      `Skipped unsupported files: ${rejectedNames.join(", ")}`,
    );
  }
}

function removeAttachment(id: string) {
  attachments.value = attachments.value.filter(
    attachment => attachment.id !== id,
  );
  if (attachments.value.length === 0) {
    clearAttachmentNotice();
  }
}

function clearAttachments() {
  attachments.value = [];
  if (fileInputRef.value) {
    fileInputRef.value.value = "";
  }
}

function submitMessage(message: string) {
  emit("submit", {
    message,
    images: toRpcImageContent(attachments.value),
  });
  inputText.value = "";
  cursorOffset.value = 0;
  dismissedMentionKey.value = null;
  clearAttachments();
  clearAttachmentNotice();
  showPalette.value = false;
  resizeTextarea();
}

function handleSubmit() {
  const text = normalizedInputText.value;
  if ((!text && !hasAttachments.value) || isDisabled.value) return;
  submitMessage(text);
}

function handleAbort() {
  if (!canAbort.value) return;
  emit("abort");
}

function handlePrimaryAction() {
  if (showStopButton.value) {
    handleAbort();
    return;
  }
  handleSubmit();
}

function handleCommandSelect(commandName: string) {
  submitMessage(`/${commandName}`);
}

function handlePaletteClose() {
  showPalette.value = false;
}

function handleMentionSelect(item: WorkspaceMentionSuggestion) {
  const mention = mentionContext.value;
  if (!mention) return;

  const nextState = applyWorkspaceMentionCompletion(
    inputText.value,
    cursorOffset.value,
    mention,
    item,
  );

  inputText.value = nextState.text;
  dismissedMentionKey.value = null;
  nextTick(() => {
    const el = textareaRef.value;
    if (!el) return;
    el.focus();
    el.setSelectionRange(nextState.cursor, nextState.cursor);
    cursorOffset.value = nextState.cursor;
    resizeTextarea();
  });
}

function handleMentionClose() {
  dismissedMentionKey.value = getMentionKey(mentionContext.value);
}

function handleModelSelect(model: RpcModelInfo) {
  emit("selectModel", model);
}

function handleThinkingLevelChange(event: Event) {
  const level = (event.target as HTMLSelectElement | null)?.value;
  if (!level) return;
  emit("selectThinkingLevel", level);
}

function handleAutoCompactionChange(event: Event) {
  emit(
    "toggleAutoCompaction",
    Boolean((event.target as HTMLInputElement | null)?.checked),
  );
}

function handleFilePickerOpen() {
  fileInputRef.value?.click();
}

function handleInputInteraction() {
  syncCursorFromTextarea();
  resizeTextarea();
}

async function handleFileInputChange(event: Event) {
  const files = (event.target as HTMLInputElement | null)?.files;
  await addAttachmentsFromFiles(files);
  if (fileInputRef.value) {
    fileInputRef.value.value = "";
  }
}

function hasFilePayload(dataTransfer: DataTransfer | null): boolean {
  return Array.from(dataTransfer?.types ?? []).includes("Files");
}

function extractPastedFiles(event: ClipboardEvent): File[] {
  const directFiles = extractSupportedImageFiles(event.clipboardData?.files);
  if (directFiles.length > 0) return directFiles;

  const pastedFiles = Array.from(event.clipboardData?.items ?? [])
    .filter(item => item.kind === "file")
    .map(item => item.getAsFile())
    .filter((file): file is File => file !== null);

  return extractSupportedImageFiles(pastedFiles);
}

async function handleInputPaste(event: ClipboardEvent) {
  const pastedFiles = extractPastedFiles(event);
  if (pastedFiles.length === 0) return;
  event.preventDefault();
  await addAttachmentsFromFiles(pastedFiles);
}

function handleDragEnter(event: DragEvent) {
  if (!hasFilePayload(event.dataTransfer)) return;
  dragDepth += 1;
  isDragActive.value = true;
}

function handleDragOver(event: DragEvent) {
  if (!hasFilePayload(event.dataTransfer)) return;
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = "copy";
  }
  isDragActive.value = true;
}

function handleDragLeave(event: DragEvent) {
  if (!hasFilePayload(event.dataTransfer)) return;
  dragDepth = Math.max(0, dragDepth - 1);
  if (dragDepth === 0) {
    isDragActive.value = false;
  }
}

async function handleDrop(event: DragEvent) {
  dragDepth = 0;
  isDragActive.value = false;
  await addAttachmentsFromFiles(event.dataTransfer?.files);
}

function handleInputKeydown(e: KeyboardEvent) {
  if (
    showPalette.value &&
    paletteRef.value &&
    (e.key === "ArrowDown" ||
      e.key === "ArrowUp" ||
      e.key === "Escape" ||
      e.key === "Enter")
  ) {
    paletteRef.value.handleKeydown(e);
    return;
  }

  if (
    showMentionPalette.value &&
    mentionPaletteRef.value &&
    (e.key === "ArrowDown" ||
      e.key === "ArrowUp" ||
      e.key === "Escape" ||
      ((props.workspaceEntriesLoading || mentionSuggestions.value.length > 0) &&
        (e.key === "Enter" || e.key === "Tab")))
  ) {
    mentionPaletteRef.value.handleKeydown(e);
    return;
  }

  if (e.key === "Escape" && props.isStreaming) {
    e.preventDefault();
    handleAbort();
    return;
  }

  if (e.key === "Enter" && !e.shiftKey && !showPalette.value) {
    e.preventDefault();
    handleSubmit();
  }
}

onBeforeUnmount(() => {
  clearAttachmentNotice();
});

resizeTextarea();
</script>

<template>
  <div class="composer-bar">
    <div class="composer-inner-wrap">
      <CommandPalette
        v-if="showPalette && commands.length > 0"
        ref="paletteRef"
        :commands="commands"
        :filter="filterText"
        @select="handleCommandSelect"
        @close="handlePaletteClose"
      />
      <WorkspaceMentionPalette
        v-else-if="showMentionPalette"
        ref="mentionPaletteRef"
        :items="mentionSuggestions"
        :loading="workspaceEntriesLoading"
        @select="handleMentionSelect"
        @close="handleMentionClose"
      />
      <div
        class="composer-dock"
        :class="{ disabled: isDisabled, 'drag-active': isDragActive }"
        @dragenter.prevent="handleDragEnter"
        @dragover.prevent="handleDragOver"
        @dragleave.prevent="handleDragLeave"
        @drop.prevent="handleDrop"
      >
        <input
          ref="fileInputRef"
          class="hidden-file-input"
          type="file"
          multiple
          :accept="COMPOSER_ATTACHMENT_ACCEPT"
          @change="handleFileInputChange"
        />

        <div v-if="attachments.length > 0" class="attachment-strip">
          <div
            v-for="attachment in attachments"
            :key="attachment.id"
            class="attachment-chip"
          >
            <img
              class="attachment-chip-preview"
              :src="attachment.previewUrl"
              :alt="attachment.name"
            />
            <div class="attachment-chip-body">
              <span class="attachment-chip-name">{{ attachment.name }}</span>
              <span class="attachment-chip-meta">
                {{ formatAttachmentSize(attachment.size) }}
              </span>
            </div>
            <button
              type="button"
              class="attachment-chip-remove"
              :aria-label="`Remove ${attachment.name}`"
              @click="removeAttachment(attachment.id)"
            >
              <X class="attachment-chip-remove-icon" aria-hidden="true" />
            </button>
          </div>
        </div>

        <div class="composer-main-row">
          <button
            type="button"
            class="attach-btn"
            :class="{ active: hasAttachments }"
            :title="hasAttachments ? 'Add more images' : 'Attach images'"
            @click="handleFilePickerOpen"
          >
            <ImagePlus class="attach-icon" aria-hidden="true" />
          </button>
          <textarea
            ref="textareaRef"
            v-model="inputText"
            class="prompt-input"
            rows="1"
            :disabled="isDisabled"
            placeholder="Ask anything, or drop an image"
            @keydown="handleInputKeydown"
            @input="handleInputInteraction"
            @keyup="handleInputInteraction"
            @click="handleInputInteraction"
            @select="handleInputInteraction"
            @focus="handleInputInteraction"
            @paste="handleInputPaste"
          />
        </div>

        <div class="composer-footer-row">
          <div class="composer-status-cluster">
            <ModelDropdown
              :models="models"
              :selected-model="selectedModel"
              :label="currentModelText"
              :disabled="isDisabled"
              @select="handleModelSelect"
            />
            <label
              class="thinking-control"
              :style="{
                '--thinking-select-width': thinkingSelectWidth,
              }"
            >
              <span class="sr-only">Thinking level</span>
              <select
                class="thinking-select"
                :value="selectedThinkingLevel"
                :disabled="isDisabled"
                @change="handleThinkingLevelChange"
              >
                <option
                  v-for="option in THINKING_LEVEL_OPTIONS"
                  :key="option.value"
                  :value="option.value"
                >
                  {{ option.label }}
                </option>
              </select>
            </label>
            <label class="toggle-chip" :class="{ disabled: isDisabled }">
              <input
                class="toggle-chip-input"
                type="checkbox"
                :checked="autoCompactionEnabled"
                :disabled="isDisabled"
                @change="handleAutoCompactionChange"
              />
              <span class="toggle-chip-label">Auto compact</span>
            </label>
          </div>
          <div class="composer-action-cluster">
            <span v-if="attachmentSummary" class="attachment-summary">
              {{ attachmentSummary }}
            </span>
            <button
              class="send-btn"
              :class="{ stop: showStopButton }"
              :disabled="showStopButton ? !canAbort : !canSubmit"
              :aria-label="showStopButton ? 'Stop response' : 'Send message'"
              @click="handlePrimaryAction"
            >
              <Square
                v-if="showStopButton"
                class="send-icon stop-icon"
                aria-hidden="true"
              />
              <CornerDownLeft v-else class="send-icon" aria-hidden="true" />
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.composer-bar {
  flex-shrink: 0;
  padding: 6px 24px 12px;
  padding-bottom: max(12px, env(safe-area-inset-bottom));
  background: linear-gradient(to top, var(--bg), var(--composer-fade));
}

.composer-inner-wrap {
  position: relative;
  width: min(960px, 100%);
  margin: 0 auto;
}

.composer-dock {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 6px;
  border-radius: 18px;
  border: 1px solid var(--border);
  background: linear-gradient(
    180deg,
    color-mix(in srgb, var(--bg-elevated) 92%, transparent),
    var(--panel)
  );
  box-shadow: 0 20px 48px rgba(0, 0, 0, 0.12);
  transition:
    border-color 0.15s ease,
    background 0.15s ease,
    box-shadow 0.15s ease;
}

.composer-dock:focus-within {
  border-color: var(--border-strong);
  background: linear-gradient(
    180deg,
    color-mix(in srgb, var(--panel) 94%, transparent),
    var(--panel-2)
  );
  box-shadow: 0 26px 56px rgba(0, 0, 0, 0.16);
}

.composer-dock.drag-active {
  border-color: color-mix(in srgb, var(--border-strong) 82%, white);
  background: linear-gradient(
    180deg,
    color-mix(in srgb, var(--panel-2) 92%, transparent),
    var(--panel)
  );
}

.composer-dock.disabled {
  opacity: 0.74;
}

.hidden-file-input {
  display: none;
}

.attachment-strip {
  display: flex;
  gap: 8px;
  overflow-x: auto;
  padding: 2px 2px 0;
  scrollbar-width: thin;
}

.attachment-chip {
  display: flex;
  align-items: center;
  gap: 10px;
  min-width: 0;
  padding: 8px 10px;
  border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
  border-radius: 14px;
  background: color-mix(in srgb, var(--panel-2) 68%, transparent);
}

.attachment-chip-preview {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  object-fit: cover;
  background: var(--panel);
  border: 1px solid color-mix(in srgb, var(--border) 72%, transparent);
}

.attachment-chip-body {
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.attachment-chip-name,
.attachment-chip-meta,
.attachment-summary {
  font-family: "SF Mono", "Monaco", "Menlo", monospace;
}

.attachment-chip-name {
  max-width: 180px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 0.72rem;
  color: var(--text);
}

.attachment-chip-meta,
.attachment-summary {
  font-size: 0.64rem;
  color: var(--text-subtle);
}

.attachment-chip-remove,
.attach-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border: 1px solid var(--border);
  background: color-mix(in srgb, var(--button-bg) 88%, transparent);
  color: var(--text-subtle);
  cursor: pointer;
  transition:
    background 0.15s ease,
    border-color 0.15s ease,
    color 0.15s ease,
    transform 0.15s ease;
}

.attachment-chip-remove {
  width: 24px;
  height: 24px;
  border-radius: 999px;
}

.attachment-chip-remove:hover,
.attach-btn:hover:not(:disabled) {
  border-color: var(--border-strong);
  background: var(--button-hover);
  color: var(--text);
}

.attachment-chip-remove-icon,
.attach-icon {
  width: 14px;
  height: 14px;
}

.composer-main-row {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  min-width: 0;
}

.attach-btn {
  width: 32px;
  height: 32px;
  border-radius: 12px;
  margin-top: 6px;
}

.attach-btn.active {
  color: var(--text);
  border-color: var(--border-strong);
}

.prompt-input {
  flex: 1;
  min-width: 0;
  max-height: 160px;
  padding: 10px 6px 8px;
  border: none;
  background: transparent;
  color: var(--text);
  font-size: 0.94rem;
  line-height: 1.5;
  outline: none;
  resize: none;
  overflow-y: hidden;
  scrollbar-gutter: stable;
}

.prompt-input:disabled,
.attach-btn:disabled {
  cursor: not-allowed;
}

.prompt-input::placeholder {
  color: var(--text-subtle);
}

.send-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 25px;
  height: 25px;
  border-radius: 12px;
  border: 1px solid var(--border);
  background: var(--button-bg);
  color: var(--text);
  cursor: pointer;
  transition:
    background 0.15s ease,
    border-color 0.15s ease,
    opacity 0.15s ease,
    transform 0.15s ease;
}

.send-btn:hover:not(:disabled) {
  background: var(--button-hover);
  border-color: var(--border-strong);
  transform: translateY(-1px);
}

.send-btn.stop {
  border-color: color-mix(in srgb, var(--error-border) 92%, var(--border));
  background: color-mix(in srgb, var(--error-bg) 82%, var(--button-bg));
  color: var(--error-text);
}

.send-btn.stop:hover:not(:disabled) {
  background: color-mix(in srgb, var(--error-bg) 92%, var(--button-hover));
  border-color: color-mix(
    in srgb,
    var(--error-border) 100%,
    var(--border-strong)
  );
}

.send-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.send-icon {
  width: 15px;
  height: 15px;
}

.stop-icon {
  width: 13px;
  height: 13px;
}

.composer-footer-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding-top: 10px;
  border-top: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
  min-width: 0;
}

.composer-status-cluster,
.composer-action-cluster {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
  flex-wrap: wrap;
}

.composer-action-cluster {
  justify-content: flex-end;
}

.thinking-control {
  position: relative;
  display: inline-flex;
  align-items: center;
}

.thinking-control::before {
  content: "Thinking";
  position: absolute;
  top: 50%;
  left: 10px;
  transform: translateY(-50%);
  font-family: "SF Mono", "Monaco", "Menlo", monospace;
  font-size: 0.62rem;
  color: var(--text-subtle);
  pointer-events: none;
}

.thinking-select {
  width: var(--thinking-select-width, auto);
  height: 26px;
  padding: 0 20px 0 68px;
  border-radius: 999px;
  border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
  background: color-mix(in srgb, var(--panel) 70%, transparent);
  color: var(--text);
  font-family: "SF Mono", "Monaco", "Menlo", monospace;
  font-size: 0.66rem;
  outline: none;
  cursor: pointer;
  appearance: none;
}

.thinking-select:hover:not(:disabled),
.thinking-select:focus {
  border-color: var(--border-strong);
  background: var(--panel-2);
}

.thinking-select:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.toggle-chip {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  height: 26px;
  padding: 0 10px;
  border-radius: 999px;
  border: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
  background: color-mix(in srgb, var(--panel) 70%, transparent);
  color: var(--text-subtle);
  cursor: pointer;
  user-select: none;
  transition:
    background 0.15s ease,
    border-color 0.15s ease,
    color 0.15s ease,
    transform 0.15s ease;
}

.toggle-chip:hover:not(.disabled),
.toggle-chip:focus-within {
  border-color: var(--border-strong);
  background: var(--panel-2);
  color: var(--text);
}

.toggle-chip.disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.toggle-chip-input {
  width: 14px;
  height: 14px;
  margin: 0;
  accent-color: var(--text);
}

.toggle-chip-input:disabled {
  cursor: not-allowed;
}

.toggle-chip-label {
  font-family: "SF Mono", "Monaco", "Menlo", monospace;
  font-size: 0.66rem;
  white-space: nowrap;
}

@media (max-width: 900px) {
  .composer-bar {
    position: sticky;
    bottom: 0;
    z-index: 10;
    padding: 10px 16px 12px;
    padding-bottom: max(12px, env(safe-area-inset-bottom));
  }

  .composer-inner-wrap {
    width: 100%;
  }

  .prompt-input {
    font-size: 16px;
  }

  .composer-footer-row {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    align-items: center;
    gap: 10px;
  }

  .composer-status-cluster {
    min-width: 0;
    flex-wrap: nowrap;
    overflow-x: auto;
    padding-bottom: 2px;
    scrollbar-width: none;
  }

  .composer-status-cluster::-webkit-scrollbar {
    display: none;
  }

  .composer-action-cluster {
    flex-shrink: 0;
    justify-content: flex-end;
  }

  .attachment-summary {
    display: none;
  }
}

@media (max-width: 640px) {
  .composer-bar {
    padding: 8px 12px 10px;
    padding-bottom: max(10px, env(safe-area-inset-bottom));
  }

  .composer-dock {
    gap: 8px;
    padding: 8px 10px;
    border-radius: 16px;
  }

  .attachment-chip {
    min-width: 200px;
  }

  .composer-main-row {
    gap: 8px;
    align-items: flex-end;
  }

  .attach-btn {
    width: 30px;
    height: 30px;
    margin-top: 0;
    border-radius: 10px;
  }

  .prompt-input {
    padding: 6px 0 4px;
    line-height: 1.45;
  }

  .composer-footer-row {
    gap: 8px;
    padding-top: 8px;
  }

  .send-btn {
    width: 32px;
    height: 32px;
    border-radius: 10px;
  }

  .thinking-select {
    width: var(--thinking-select-width, auto);
    max-width: 132px;
  }
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>

// packages/svelte/src/components/ComposerBar.svelte
<script lang="ts">
  import type {
    RpcGitRepoState,
    RpcImageContent,
    RpcSlashCommand,
    RpcThinkingLevel,
    RpcWorkspaceEntry,
  } from "@pi-web/bridge/types";
  import Check from "lucide-svelte/icons/check";
  import CornerDownLeft from "lucide-svelte/icons/corner-down-left";
  import ImagePlus from "lucide-svelte/icons/image-plus";
  import Square from "lucide-svelte/icons/square";
  import X from "lucide-svelte/icons/x";
  import type { ConnectionStatus } from "../composables/bridgeStore.svelte";
  import { COMPOSER_ATTACHMENT_ACCEPT, formatAttachmentSize } from "../utils/attachments";
  import type { RpcModelInfo } from "../utils/models";
  import CommandPalette from "./CommandPalette.svelte";
  import GitBranchDropdown from "./GitBranchDropdown.svelte";
  import ImageLightbox from "./ImageLightbox.svelte";
  import ModelDropdown from "./ModelDropdown.svelte";
  import ThinkingLevelDropdown from "./ThinkingLevelDropdown.svelte";
  import WorkspaceMentionPalette from "./WorkspaceMentionPalette.svelte";
  import { createComposerBarState } from "./composerBarState.svelte";

  let {
    connectionStatus = "disconnected" as ConnectionStatus,
    isStreaming = false,
    isDebugMode = false,
    isDebugSession = false,
    commands = [] as readonly RpcSlashCommand[],
    workspaceEntries = [] as readonly RpcWorkspaceEntry[],
    workspaceEntriesLoading = false,
    workspaceContextKey = null as string | null,
    ensureWorkspaceEntries = ((_force?: boolean) => Promise.resolve([] as RpcWorkspaceEntry[])) as (force?: boolean) => Promise<RpcWorkspaceEntry[]>,
    models = [] as readonly RpcModelInfo[],
    selectedModel = null as RpcModelInfo | null,
    thinkingLevel = null as RpcThinkingLevel | null,
    autoCompactionEnabled = false,
    prefillText = null as string | null,
    revision = null as { entryId: string; text: string; preview: string; hasImages: boolean; images: RpcImageContent[] } | null,
    pendingMessageCount = 0,
    editQueuedPayload = null as { text: string; images: RpcImageContent[] } | null,
    onInteraction = (() => {}) as () => void,
    onSubmit = ((_: { message: string; images: RpcImageContent[]; revisionEntryId?: string; steer?: boolean }) => {}) as (payload: { message: string; images: RpcImageContent[]; revisionEntryId?: string; steer?: boolean }) => void,
    onAbort = (() => {}) as () => void,
    onCancelRevision = (() => {}) as () => void,
    onSelectModel = ((_: RpcModelInfo) => {}) as (model: RpcModelInfo) => void,
    onSelectThinkingLevel = ((_: RpcThinkingLevel) => {}) as (level: RpcThinkingLevel) => void,
    onToggleAutoCompaction = ((_: boolean) => {}) as (enabled: boolean) => void,
    gitBranch = null as string | null,
    gitRepoState = null as RpcGitRepoState | null,
    gitRepoLoading = false,
    gitBranchSwitching = false,
    gitActionsDisabled = false,
    refreshGitRepoState = (_?: boolean) => Promise.resolve(null as RpcGitRepoState | null),
    switchGitBranch = (_: string) => Promise.resolve(null as RpcGitRepoState | null),
    createGitBranch = (_: string) => Promise.resolve(null as RpcGitRepoState | null),
  } = $props();

  let composerPlaceholder = $derived(
    isDebugMode && isDebugSession
      ? "Use /fixture, /tps, /json, or type synthetic markdown"
      : "Ask anything, or drop an image",
  );

  // ---- DOM refs (must stay in .svelte for bind:this) ----
  let composerRootRef = $state<HTMLDivElement | null>(null);
  let textareaRef = $state<HTMLTextAreaElement | null>(null);
  let fileInputRef = $state<HTMLInputElement | null>(null);
  let commandPaletteRef = $state<CommandPalette | null>(null);
  let mentionPaletteRef = $state<WorkspaceMentionPalette | null>(null);

  // ---- reactive primitives owned by the component (needed for bind:) ----
  let inputText = $state("");
  let cursorOffset = $state(0);

  // ---- state module (reads/writes inputText & cursorOffset through $rx) ----
  const composer = createComposerBarState(
    {
      get connectionStatus() { return connectionStatus; },
      get isStreaming() { return isStreaming; },
      get isDebugMode() { return isDebugMode; },
      get commands() { return commands; },
      get workspaceEntries() { return workspaceEntries; },
      get workspaceEntriesLoading() { return workspaceEntriesLoading; },
      get workspaceContextKey() { return workspaceContextKey; },
      get ensureWorkspaceEntries() { return ensureWorkspaceEntries; },
      get models() { return models; },
      get selectedModel() { return selectedModel; },
      get thinkingLevel() { return thinkingLevel; },
      get autoCompactionEnabled() { return autoCompactionEnabled; },
      get prefillText() { return prefillText; },
      get revision() { return revision; },
      get pendingMessageCount() { return pendingMessageCount; },
      get editQueuedPayload() { return editQueuedPayload; },
    },
    {
      get onSubmit() { return onSubmit; },
      get onAbort() { return onAbort; },
      get onCancelRevision() { return onCancelRevision; },
      get onSelectModel() { return onSelectModel; },
      get onSelectThinkingLevel() { return onSelectThinkingLevel; },
      get onToggleAutoCompaction() { return onToggleAutoCompaction; },
    },
    {
      get inputText() { return inputText; },
      set inputText(v: string) { inputText = v; },
      get cursorOffset() { return cursorOffset; },
      set cursorOffset(v: number) { cursorOffset = v; },
    },
  );

  // ---- event handler glue (wires state methods to DOM refs) ----

  function handleFilePickerOpen() {
    composer.handleFilePickerOpen(fileInputRef);
  }

  async function handleFileInputChange(event: Event) {
    await composer.handleFileInputChange(event, fileInputRef);
  }

  function handleInputInteraction() {
    composer.handleInputInteraction(textareaRef);
    onInteraction();
  }

  function handleInputCompositionStart() {
    composer.handleInputCompositionStart();
  }

  function handleInputCompositionEnd() {
    composer.handleInputCompositionEnd(textareaRef);
  }

  async function handleInputPaste(event: ClipboardEvent) {
    await composer.handleInputPaste(event);
  }

  function handleInputKeydown(e: KeyboardEvent) {
    composer.handleInputKeydown(e, {
      textareaEl: textareaRef,
      commandPaletteEl: commandPaletteRef,
      mentionPaletteEl: mentionPaletteRef,
    }, isStreaming);
  }

  function handleCommandSelect(commandName: string) {
    composer.handleCommandSelect(commandName, textareaRef);
  }

  function handleMentionSelect(item: Parameters<typeof composer.handleMentionSelect>[0]) {
    composer.handleMentionSelect(item, textareaRef);
  }

  function handleCancelRevision() {
    composer.handleCancelRevision(fileInputRef, textareaRef, composerRootRef);
  }

  function handlePrimaryAction() {
    if (composer.showStopButton) {
      composer.handleAbortAction();
      return;
    }
    composer.handleSubmit(false, fileInputRef, textareaRef);
  }

  // ---- effects that need DOM refs ----

  $effect(() => {
    // Resize textarea on input change
    void inputText;
    composer.resizeTextarea(textareaRef);
  });

  $effect(() => {
    if (typeof prefillText === "string") {
      composer.applyExternalText(prefillText, {
        fileInputEl: fileInputRef,
        textareaEl: textareaRef,
        rootEl: composerRootRef,
      });
    }
  });

  $effect(() => {
    void editQueuedPayload;
    if (editQueuedPayload) {
      composer.focusComposer({
        textareaEl: textareaRef,
        rootEl: composerRootRef,
        reveal: true,
      });
    }
  });

  // Initial resize
  $effect(() => {
    composer.resizeTextarea(textareaRef);
  });
</script>

<div bind:this={composerRootRef} class="composer-bar">
  <div class="composer-inner-wrap">
    {#if composer.showCommandPalette}
      <CommandPalette
        bind:this={commandPaletteRef}
        commands={composer.availableSlashCommands}
        filter={composer.commandContext?.query ?? ""}
        isDebugMode={isDebugMode}
        onSelect={handleCommandSelect}
        onClose={composer.handleCommandClose}
      />
    {:else if composer.showMentionPalette}
      <WorkspaceMentionPalette
        bind:this={mentionPaletteRef}
        items={composer.mentionSuggestions}
        loading={workspaceEntriesLoading}
        onSelect={handleMentionSelect}
        onClose={composer.handleMentionClose}
      />
    {/if}

    <div
      class="composer-dock"
      class:disabled={composer.isDisabled}
      class:drag-active={composer.isDragActive}
      role="region"
      aria-label="Message composer"
      ondragenter={composer.handleDragEnter}
      ondragover={composer.handleDragOver}
      ondragleave={composer.handleDragLeave}
      ondrop={composer.handleDrop}
    >
      {#if revision}
        <div class="revision-banner">
          <div class="revision-banner-copy">
            <p class="revision-preview">{revision.preview}</p>
          </div>
          <button
            type="button"
            class="revision-cancel-button"
            onclick={handleCancelRevision}
          >
            Cancel
          </button>
        </div>
      {/if}

      <input
        bind:this={fileInputRef}
        class="hidden-file-input"
        type="file"
        multiple
        accept={COMPOSER_ATTACHMENT_ACCEPT}
        onchange={handleFileInputChange}
      />

      {#if composer.attachments.length > 0}
        <div class="attachment-strip">
          {#each composer.attachments as attachment, index (attachment.id)}
            <div class="attachment-chip">
              <button
                type="button"
                class="attachment-chip-open"
                aria-label={`View ${attachment.name}`}
                onclick={() => composer.openAttachmentLightbox(index)}
              >
                <img
                  class="attachment-chip-preview"
                  src={attachment.previewUrl}
                  alt={attachment.name}
                />
                <div class="attachment-chip-body">
                  <span class="attachment-chip-name">{attachment.name}</span>
                  <span class="attachment-chip-meta">
                    {formatAttachmentSize(attachment.size)}
                  </span>
                </div>
              </button>
              <button
                type="button"
                class="attachment-chip-remove"
                aria-label={`Remove ${attachment.name}`}
                onclick={() => composer.removeAttachment(attachment.id)}
              >
                <X class="attachment-chip-remove-icon" aria-hidden="true" size={14} />
              </button>
            </div>
          {/each}
        </div>
      {/if}

      <div class="composer-main-row">
        <button
          type="button"
          class="attach-btn"
          title={composer.hasAttachments ? "Add more images" : "Attach images"}
          onclick={handleFilePickerOpen}
        >
          <ImagePlus class="attach-icon" aria-hidden="true" size={16} />
        </button>
        <textarea
          bind:this={textareaRef}
          bind:value={inputText}
          class="prompt-input"
          rows="1"
          disabled={composer.isDisabled}
          placeholder={composerPlaceholder}
          onkeydown={handleInputKeydown}
          oninput={handleInputInteraction}
          onkeyup={handleInputInteraction}
          onclick={handleInputInteraction}
          oncompositionstart={handleInputCompositionStart}
          oncompositionend={handleInputCompositionEnd}
          onselect={handleInputInteraction}
          onfocus={handleInputInteraction}
          onpaste={handleInputPaste}
        ></textarea>
      </div>

      <div class="composer-footer-row">
        <div class="composer-status-cluster">
          {#if !isDebugSession}
            <GitBranchDropdown
              label={gitBranch}
              repoState={gitRepoState}
              loading={gitRepoLoading}
              switching={gitBranchSwitching}
              disabled={gitActionsDisabled}
              refresh={refreshGitRepoState}
              switchBranch={switchGitBranch}
              createBranch={createGitBranch}
            />
          {/if}
          <ModelDropdown
            {models}
            {selectedModel}
            label={composer.currentModelText}
            disabled={composer.isDisabled}
            onSelect={(model: RpcModelInfo) => onSelectModel(model)}
          />
          <ThinkingLevelDropdown
            value={thinkingLevel}
            disabled={composer.isDisabled}
            onSelect={(level: RpcThinkingLevel) => onSelectThinkingLevel(level)}
          />
          <button
            type="button"
            class="toggle-chip"
            class:disabled={composer.isDisabled}
            class:checked={autoCompactionEnabled}
            disabled={composer.isDisabled}
            aria-pressed={autoCompactionEnabled}
            onclick={composer.handleAutoCompactionToggle}
          >
            <span class="toggle-chip-icon" aria-hidden="true">
              {#if autoCompactionEnabled}
                <Check size={11} strokeWidth={2.5} />
              {/if}
            </span>
            <span class="toggle-chip-label">Auto compact</span>
          </button>
        </div>
        <div class="composer-action-cluster">
          {#if composer.attachmentSummary}
            <span class="attachment-summary">{composer.attachmentSummary}</span>
          {/if}
          {#if composer.hasPendingMessages}
            <div
              class="pending-queue-indicator"
              title={`${pendingMessageCount} message${pendingMessageCount > 1 ? "s" : ""} queued`}
            >
              <span class="pending-pulse"></span>
              <span class="pending-label">{pendingMessageCount}</span>
            </div>
          {/if}
          <button
            class="send-btn"
            class:stop={composer.showStopButton}
            disabled={composer.showStopButton ? !composer.canAbort : !composer.canSubmit}
            aria-label={composer.showStopButton ? "Stop response" : "Send message"}
            onclick={handlePrimaryAction}
          >
            {#if composer.showStopButton}
              <Square class="send-icon stop-icon" aria-hidden="true" size={13} />
            {:else}
              <CornerDownLeft class="send-icon" aria-hidden="true" size={15} />
            {/if}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<ImageLightbox
  open={composer.lightboxOpen}
  images={composer.lightboxImages}
  index={composer.lightboxAttachmentIndex}
  onClose={composer.closeAttachmentLightbox}
  onPrevious={composer.showPreviousAttachmentLightboxImage}
  onNext={composer.showNextAttachmentLightboxImage}
/>

<style>
  .composer-bar {
    flex-shrink: 0;
    padding: 6px 24px 12px;
    padding-bottom: max(12px, env(safe-area-inset-bottom));
    background: var(--bg);
  }

  .composer-inner-wrap {
    position: relative;
    width: min(960px, 100%);
    margin: 0 auto;
  }

  .composer-dock {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 6px;
    border-radius: 18px;
    border: 1px solid var(--border);
    background: var(--bg);
    transition:
      border-color 0.15s ease,
      background 0.15s ease;
  }

  .revision-banner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 10px 12px;
    border-radius: 14px;
    border: 1px solid color-mix(in srgb, var(--border-strong) 82%, transparent);
    background: color-mix(in srgb, var(--panel-2) 88%, transparent);
  }

  .revision-banner-copy { min-width: 0; }

  .revision-preview {
    margin: 0;
    font-size: 0.82rem;
    line-height: 1.45;
    color: var(--text);
  }

  .revision-cancel-button {
    flex-shrink: 0;
    height: 28px;
    padding: 0 10px;
    border-radius: 999px;
    border: 1px solid var(--border);
    background: var(--bg);
    color: var(--text-muted);
    font-size: 0.7rem;
    cursor: pointer;
    transition:
      border-color 0.12s ease,
      color 0.12s ease,
      background 0.12s ease;
  }

  .revision-cancel-button:hover {
    border-color: var(--border-strong);
    background: var(--bg);
    color: var(--text);
  }

  .composer-dock:focus-within {
    border-color: var(--border-strong);
    background: var(--bg);
  }

  .composer-dock.drag-active {
    border-color: color-mix(in srgb, var(--accent) 36%, var(--border-strong));
    background: var(--bg);
  }

  .composer-dock.disabled { opacity: 0.74; }

  .hidden-file-input { display: none; }

  .attachment-strip {
    display: flex;
    gap: 8px;
    overflow-x: auto;
    padding: 2px 2px 0;
    scrollbar-width: thin;
  }

  .attachment-chip {
    display: flex;
    align-items: center;
    gap: 10px;
    min-width: 0;
    padding: 8px 10px;
    border: 1px solid color-mix(in srgb, var(--border) 82%, transparent);
    border-radius: 14px;
    background: color-mix(in srgb, var(--panel) 74%, transparent);
  }

  .attachment-chip-open {
    display: flex;
    align-items: center;
    gap: 10px;
    min-width: 0;
    padding: 0;
    border: none;
    background: transparent;
    color: inherit;
    cursor: zoom-in;
    text-align: left;
  }

  .attachment-chip-preview {
    width: 36px;
    height: 36px;
    border-radius: 10px;
    object-fit: cover;
    background: var(--panel);
    border: 1px solid color-mix(in srgb, var(--border) 68%, transparent);
  }

  .attachment-chip-body {
    display: flex;
    flex-direction: column;
    min-width: 0;
  }

  .attachment-chip-name,
  .attachment-chip-meta,
  .attachment-summary { font-family: var(--pi-font-mono); }

  .pending-queue-indicator {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    height: 22px;
    padding: 0 8px;
    border-radius: 999px;
    border: 1px solid color-mix(in srgb, var(--border-strong) 60%, transparent);
    background: color-mix(in srgb, var(--panel-2) 80%, transparent);
    color: var(--text-subtle);
    font-size: 0.68rem;
    user-select: none;
  }

  .pending-pulse {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    background: var(--warning);
    animation: pending-pulse 1.4s ease-in-out infinite;
  }

  .pending-label {
    font-weight: 600;
    font-variant-numeric: tabular-nums;
    line-height: 1;
  }

  @keyframes pending-pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.5; transform: scale(0.85); }
  }

  .attachment-chip-name {
    max-width: 180px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 0.72rem;
    color: var(--text);
  }

  .attachment-chip-meta,
  .attachment-summary {
    font-size: 0.64rem;
    color: var(--text-subtle);
  }

  .attachment-chip-remove {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 24px;
    height: 24px;
    border-radius: 999px;
    border: 1px solid color-mix(in srgb, var(--border) 78%, transparent);
    background: transparent;
    color: var(--text-subtle);
    cursor: pointer;
    transition:
      background 0.15s ease,
      border-color 0.15s ease,
      color 0.15s ease;
  }

  .attach-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 24px;
    height: 24px;
    margin-top: 8px;
    border-radius: 10px;
    border: none;
    background: var(--bg);
    color: var(--text-subtle);
    cursor: pointer;
    transition:
      background 0.15s ease,
      border-color 0.15s ease,
      color 0.15s ease,
      opacity 0.15s ease;
  }

  .attachment-chip-open:hover .attachment-chip-name,
  .attachment-chip-open:focus-visible .attachment-chip-name,
  .attachment-chip-remove:hover,
  .attach-btn:hover:not(:disabled) {
    color: var(--text);
  }

  .attachment-chip-open:hover .attachment-chip-preview,
  .attachment-chip-open:focus-visible .attachment-chip-preview,
  .attachment-chip-remove:hover,
  .attach-btn:hover:not(:disabled) {
    background: var(--bg);
  }

  .attachment-chip-open:focus-visible,
  .attachment-chip-remove:focus-visible,
  .attach-btn:focus-visible {
    outline: 2px solid color-mix(in srgb, var(--accent) 54%, white 12%);
    outline-offset: 2px;
  }

  .composer-main-row {
    display: flex;
    align-items: flex-start;
    gap: 6px;
    min-width: 0;
  }

  .prompt-input {
    display: block;
    box-sizing: border-box;
    flex: 1;
    min-width: 0;
    max-height: 160px;
    padding: 9px 0 10px;
    border: none;
    background: transparent;
    color: var(--text);
    font-family: var(--pi-font-sans);
    font-size: 0.94rem;
    font-weight: 400;
    line-height: 1.55;
    outline: none;
    resize: none;
    overflow-y: hidden;
    scrollbar-gutter: stable;
  }

  .prompt-input:disabled,
  .attach-btn:disabled { cursor: not-allowed; }

  .prompt-input::placeholder {
    color: var(--text-subtle);
    line-height: inherit;
  }

  .send-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 25px;
    height: 25px;
    border-radius: 12px;
    border: none;
    background: var(--bg);
    color: var(--text);
    cursor: pointer;
    transition:
      background 0.15s ease,
      border-color 0.15s ease,
      opacity 0.15s ease,
      transform 0.15s ease;
  }

  .send-btn:hover:not(:disabled) {
    background: var(--bg);
    transform: translateY(-1px);
  }

  .send-btn.stop {
    background: var(--bg);
    color: var(--error-text);
  }

  .send-btn.stop:hover:not(:disabled) {
    background: var(--bg);
  }

  .send-btn:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .composer-footer-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding-top: 10px;
    border-top: 1px solid color-mix(in srgb, var(--border) 84%, transparent);
    min-width: 0;
  }

  .composer-status-cluster,
  .composer-action-cluster {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
    flex-wrap: wrap;
  }

  .composer-action-cluster { justify-content: flex-end; }

  .toggle-chip {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    height: 26px;
    padding: 0 10px;
    border-radius: 999px;
    border: none;
    background: var(--bg);
    color: var(--text-subtle);
    cursor: pointer;
    user-select: none;
    font: inherit;
    transition:
      background 0.15s ease,
      border-color 0.15s ease,
      color 0.15s ease,
      transform 0.15s ease;
  }

  .toggle-chip:hover:not(.disabled) {
    background: var(--bg);
    color: var(--text);
  }

  .toggle-chip:focus-visible {
    background: var(--bg);
    color: var(--text);
    outline: none;
  }

  .toggle-chip.disabled { opacity: 0.45; cursor: not-allowed; }

  .toggle-chip-icon {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 14px;
    height: 14px;
    border-radius: 4px;
    border: 1px solid color-mix(in srgb, var(--border-strong) 72%, transparent);
    background: transparent;
    color: var(--bg);
    transition:
      border-color 0.15s ease,
      background 0.15s ease,
      color 0.15s ease;
  }

  .toggle-chip.checked {
    color: var(--text);
  }

  .toggle-chip.checked .toggle-chip-icon {
    border-color: color-mix(in srgb, var(--text) 72%, transparent);
    background: var(--text);
    color: var(--bg);
  }

  .toggle-chip-label {
    font-family: var(--pi-font-sans);
    font-size: 0.66rem;
    white-space: nowrap;
  }

  @media (max-width: 900px) {
    .composer-bar {
      position: sticky;
      bottom: 0;
      z-index: 10;
      padding: 10px 16px 12px;
      padding-bottom: max(12px, env(safe-area-inset-bottom));
    }

    .composer-inner-wrap { width: 100%; }
    .prompt-input { font-size: 16px; }

    .composer-footer-row {
      display: grid;
      grid-template-columns: minmax(0, 1fr) auto;
      align-items: center;
      gap: 10px;
    }

    .composer-status-cluster {
      min-width: 0;
      flex-wrap: nowrap;
      overflow-x: auto;
      padding-bottom: 2px;
      scrollbar-width: none;
    }

    .composer-status-cluster::-webkit-scrollbar { display: none; }

    .composer-action-cluster {
      flex-shrink: 0;
      justify-content: flex-end;
    }

    .attachment-summary { display: none; }
  }

  @media (max-width: 640px) {
    .composer-bar {
      padding: 8px 12px 10px;
      padding-bottom: max(10px, env(safe-area-inset-bottom));
    }

    .revision-banner { flex-direction: column; }
    .revision-cancel-button { align-self: flex-start; }

    .composer-dock { gap: 8px; padding: 8px 10px; border-radius: 16px; }
    .attachment-chip { min-width: 200px; }

    .composer-main-row { gap: 8px; align-items: flex-end; }

    .attach-btn {
      width: 26px;
      height: 26px;
      margin-top: 0;
      border-radius: 10px;
    }

    .prompt-input { padding: 5px 0 6px; line-height: 1.5; }
    .composer-footer-row { gap: 8px; padding-top: 8px; }

    .send-btn { width: 32px; height: 32px; border-radius: 10px; }
  }
</style>
